default_platform(:android)

platform :android do
  desc "Build DEV APK"
  lane :dev do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build apk --debug --flavor dev -t lib/main_dev.dart"
    firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        apk_path: "../build/app/outputs/flutter-apk/app-dev-debug.apk",
        groups: "me",
        release_notes: "DEV build via Fastlane"
     )
  end
end

platform :android do
  desc "Build PROD AAB (Release) & Distribute via Firebase"
  lane :prod_release do

    sh "flutter clean"
    sh "flutter pub get"

    sh "flutter build appbundle \
        --release \
        --flavor prod \
        -t lib/main_prod.dart"

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      android_artifact_type: "AAB",
      android_artifact_path: "../build/app/outputs/bundle/prodRelease/app-prod-release.aab",
      groups: "me",
      release_notes: "PROD AAB via Fastlane"
    )
  end
end


